application: 0147bbh
version: 2
runtime: python
api_version: 1

default_expiration: '30d'

skip_files:
- flash/.*
- .*\.git.*
- .*\.DS_Store.*
- .*\.less.*
- .*\.sh.*
- .*js/(.+packaged\.js|.+(?<!packaged)\.js)

handlers:
- url: /assets
  static_dir: static/assets
- url: /humans.txt
  static_files: static/assets/humans.txt
  upload: static/assets/humans.txt
- url: .*
  script: main.py
