application: 0147bbh
version: 1
runtime: python
api_version: 1

default_expiration: '30d'

skip_files:
- flash/.*
- .*\.git.*
- .*\.less.*
- .*js/(.+packaged\.js|.+(?<!packaged)\.js)

handlers:
- url: /assets
  static_dir: static/assets
  
- url: /
  static_files: template/public.html
  upload: template/public.html
  
- url: .*
  script: main.py
