tokbox:
  api_key: 4901211
  secret: 2089103c3f545555cda734358711f685ec7355f6
  props: '{ width: 400, height: 300 }'
  session_id: 2_MX40OTAxMjExfn4yMDExLTA5LTI2IDIwOjEyOjUyLjkzNjk2NyswMDowMH4wLjcxMTkwMDc3MzU5fg
cookie_name: FLokfGUUiprgVdCUHSKZvxb8qV5yWVjA0WS3z6UXJliYCXRAsSoJJ4BCi6GcTZb
pre:
  username: Christy
  password: mklohyzaxiW9VMIi1hTLmRoX8tL3bPU4bQIoAjyHH9Ih6GaBtUpymkFR49yO4qd
role:
  presenter: MODERATOR
  participant: PUBLISHER
  public: SUBSCRIBER
