tokbox:
  api_key: YOUR_API_KEY
  secret: YOUR_SECRET
  props: '{ width: 400, height: 300 }'
  session_id: YOUR_SESSION_ID
cookie_name: A_COOKIE_NAME
pre:
  username: USERNAME
  password: PASSWORD
role:
  presenter: MODERATOR
  participant: PUBLISHER
  public: SUBSCRIBER
